name: terraform-apply

on: [push]


env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }} 


jobs:

        ejecucion-apply:
            runs-on: ubuntu-latest

            steps:
            - uses: actions/checkout@v4  
            - run: terraform init          
            - run: terraform apply -auto-approve
            - run: 
                 echo Se ha ejecutado un terraform apply